export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  USER: "USER",
  ADMIN_PPID: "admin_ppid",
  K_SDM: "K_SDM",
  K_KUL: "K_KUL",
  K_RDT: "K_RDT",
  K_TEKHUM: "K_TEKHUM",
  SEKRETARIS: "SEKRETARIS",
};
 

export const JABATAN = {
  KETUA: "KETUA",
  ANGGOTA: "ANGGOTA",
  SEKRETARIS: "SEKRETARIS",

  KASUBBAG_HUKUM_DAN_SDM: "KASUBBAG_HUKUM_DAN_SDM",

  KASUBBAG_PERENCANAAN_DATA_DAN_INFORMASI:
    "KASUBBAG_PERENCANAAN_DATA_DAN_INFORMASI",

  PENELAAH_TEKNIS_KEBIJAKAN: "PENELAAH_TEKNIS_KEBIJAKAN",

  PENATA_KELOLA_SISTEM_DAN_TEKNOLOGI_INFORMASI:
    "PENATA_KELOLA_SISTEM_DAN_TEKNOLOGI_INFORMASI",

  PENYUSUN_MATERI_HUKUM_DAN_PERUNDANG_UNDANGAN:
    "PENYUSUN_MATERI_HUKUM_DAN_PERUNDANG_UNDANGAN",

  PENATA_KELOLA_PEMILU: "PENATA_KELOLA_PEMILU",

  ARSIPARIS_TERAMPIL: "ARSIPARIS_TERAMPIL",

  OPERATOR_LAYANAN_OPERASIONAL: "OPERATOR_LAYANAN_OPERASIONAL",

  ADMINISTRASI_PERKANTORAN: "ADMINISTRASI_PERKANTORAN",
};
